name: flutter_routing_sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  connectivity_plus:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_keyboard_visibility:
  flutter_localizations:
    sdk: flutter
  flutter_spinkit:
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  gap:
  go_router:
  hooks_riverpod: ^2.0.0-dev.9

dev_dependencies:
  build_runner:
  flutter_driver:
    sdk: flutter
  flutter_lints:
  flutter_test:
    sdk: flutter
  pedantic_mono:

flutter:
  uses-material-design: true
